#! /bin/bash

function header {
    echo "Pre-push hook for Letscode REST API"
}

function lint {
    echo -e 'Checking for syntax errors...\c'
    for file in `find src/. test/.`
    do
        EXTENSION="${file##*.}"

        if [ "$EXTENSION" == "php" ] || [ "$EXTENSION" == "phtml" ]
        then
            php -l $file > /dev/null 2>&1
            if [ $? == 0 ]
            then
                failed
            fi
        fi
    done
    pass
}

function git_checker {
    echo -e 'Checking working directory...\c'
    if [ -n "$(git status --porcelain)" ]; then
      echo -e "\e[31mplease commit/stash your changes first!\e[0m\n"
      mplayer support/git/sad-trompone.mp3 > /dev/null 2>&1
      exit 1
    else
      echo -e "\e[32mclean!\e[0m\n"
    fi
}

function checkstyle {
    echo -e 'Running codesniffer...\c'
    vendor/squizlabs/php_codesniffer/scripts/phpcs src --standard=PSR2 > /dev/null
    check $?
}

function mess_detector {
    echo -e 'Running mess detector...\c'
    vendor/phpmd/phpmd/src/bin/phpmd src text cleancode,naming,controversial,design --suffixes php,phtml  > /dev/null
    check $?
}

function test {
    echo -e 'Running tests...\c'
    vendor/phpunit/phpunit/phpunit > /dev/null
    check $?
}

function check {
    if [ $1 == 0 ]; then
        pass
    else
        failed
    fi
}

function pass {
    echo -e "\e[32mpassed!\e[0m\n"
}

function failed {
    echo -e "\e[31mfailed!\e[0m\n"
    mplayer support/git/sad-trompone.mp3  > /dev/null &
    exit 1
}

header
git_checker
checkstyle
mess_detector
test
exit 0